apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bf0fsdc5j-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:22b576d1bfc9db5849578730e2a678cad00b5033@sha256:6e52570f21cfc66f4cc0bd171756237f76e0d555627730e76574d8df1f0b6c1f
          name: container-image
