apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bf0fsdc5j-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:c855d05739ab7ec1b262197bd555ec1d19c6f1ca@sha256:d20aa13c6090530518019a195eb10c5b67b207728d7ae922206ceed33b16b29c
          name: container-image
