apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bf0fsdc5j-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bf0fsdc5j-go 
  name: bf0fsdc5j-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bf0fsdc5j-go 
